version: '3'
services:
  nors:
    build:
      context: .
    volumes:
      - .:/app
  build-wheels-for-python:
    build:
      context: bindings/python3
      dockerfile: Dockerfile
    volumes:
      - ./:/io