[package]
name = "nors-py"
version = "0.1.0"
authors = ["booink.work@gmail.com"]
edition = "2018"

[lib]
name = "nors_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.13.1", extension-module = ["extension-module"], default = ["extension-module"] }
nors = { path = "../../" }
